In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
df = pd.read_csv('emails.csv')
df

,Email No.,the,to,ect,and,for,of,a,you,hou,...,connevey,jay,valued,lay,infrastructure,military,allowing,ff,dry,Prediction
0,Email 1,0,0,1,0,0,0,2,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Email 2,8,13,24,6,6,2,102,1,27,...,0,0,0,0,0,0,0,1,0,0
2,Email 3,0,0,1,0,0,0,8,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Email 4,0,5,22,0,5,1,51,2,10,...,0,0,0,0,0,0,0,0,0,0
4,Email 5,7,6,17,1,5,2,57,0,9,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5167,Email 5168,2,2,2,3,0,0,32,0,0,...,0,0,0,0,0,0,0,0,0,0
5168,Email 5169,35,27,11,2,6,5,151,4,3,...,0,0,0,0,0,0,0,1,0,0
5169,Email 5170,0,0,1,1,0,0,11,0,0,...,0,0,0,0,0,0,0,0,0,1
5170,Email 5171,2,7,1,0,2,1,28,2,0,...,0,0,0,0,0,0,0,1,0,1
5171,Email 5172,22,24,5,1,6,5,148,8,2,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
df.shape

(5172, 3002)

In [ ]:
df.isnull().sum()

Email No.     0
the           0
to            0
ect           0
and           0
             ..
military      0
allowing      0
ff            0
dry           0
Prediction    0
Length: 3002, dtype: int64

In [ ]:
X = df.iloc[:,1:3001]
X.shape

(5172, 3000)

In [ ]:
Y = df.iloc[:,-1]
Y.shape

(5172,)

In [ ]:
X_train,X_test,y_train,y_test= train_test_split(X,Y,test_size=0.2)
model_list = []
model_test_acc = []
model_train_acc = []
model_recall = []
model_precision = []
model_F1 = []
model_time = []

In [ ]:
from sklearn.naive_bayes import GaussianNB , MultinomialNB
from time import process_time
from sklearn.metrics import accuracy_score, recall_score ,precision_score ,f1_score

start = process_time()
classifier = GaussianNB()
classifier.fit(X_train, y_train)
GauNB_pred = classifier.predict(X_test)
end = process_time()

model_list.append("GaussianNB")
model_test_acc.append(accuracy_score(y_true = y_test, y_pred=GauNB_pred))
model_train_acc.append(accuracy_score(y_true = y_train, y_pred=classifier.predict(X_train)))
model_recall.append(recall_score(y_true = y_test, y_pred=GauNB_pred,))
model_precision.append(precision_score(y_true = y_test, y_pred=GauNB_pred,))
model_F1.append(f1_score(y_true = y_test, y_pred=GauNB_pred))
model_time.append(str((end-start)))

print("GaussianNB train acc:",accuracy_score(y_true = y_train, y_pred=classifier.predict(X_train)))
print("GaussianNB test acc:",accuracy_score(y_true = y_test, y_pred=GauNB_pred))
print("GaussianNB Recall :",(recall_score(y_true = y_test, y_pred=GauNB_pred,)))
print("GaussianNB precision :",(precision_score(y_true = y_test, y_pred=GauNB_pred)))
print("GaussianNB F1 :",(f1_score(y_true = y_test, y_pred=GauNB_pred)))
print("GaussianNB Time :",str(end-start),"\n")


start = process_time()
classifier1 = MultinomialNB()
classifier1.fit(X_train, y_train)
MulNB_pred = classifier1.predict(X_test)
end = process_time()

model_list.append("MultinomialNB")
model_test_acc.append(accuracy_score(y_true = y_test, y_pred=MulNB_pred))
model_train_acc.append(accuracy_score(y_true = y_train, y_pred=classifier1.predict(X_train)))
model_recall.append(recall_score(y_true = y_test, y_pred=MulNB_pred))
model_precision.append(precision_score(y_true = y_test, y_pred=MulNB_pred))
model_F1.append(f1_score(y_true = y_test, y_pred=MulNB_pred))
model_time.append(str((end-start)))

print("MultinomialNB train acc:",accuracy_score(y_true = y_train, y_pred=classifier1.predict(X_train)))
print("MultinomialNB test acc:",accuracy_score(y_true = y_test, y_pred=MulNB_pred))
print("MultinomialNB Recall :",(recall_score(y_true = y_test, y_pred=MulNB_pred,)))
print("MultinomialNB precision :",(precision_score(y_true = y_test, y_pred=MulNB_pred)))
print("MultinomialNB F1 :",(f1_score(y_true = y_test, y_pred=MulNB_pred)))
print("MultinomialNB Time :",str(end-start),"\n")

GaussianNB train acc: 0.9625332366449117
GaussianNB test acc: 0.9536231884057971
GaussianNB Recall : 0.939873417721519
GaussianNB precision : 0.911042944785276
GaussianNB F1 : 0.9252336448598131
GaussianNB Time : 0.3719567710000007

MultinomialNB train acc: 0.9456127628716461
MultinomialNB test acc: 0.9487922705314009
MultinomialNB Recall : 0.9462025316455697
MultinomialNB precision : 0.8925373134328358
MultinomialNB F1 : 0.9185867895545315
MultinomialNB Time : 0.1753831309999967

In [ ]:
from sklearn.svm import SVC


best_acc = 0
best_model = ""
SVM_list = ['linear', 'poly', 'rbf', 'sigmoid']
for model in SVM_list:
  start = process_time()
  svm_model = SVC(kernel = model, random_state = 0)
  svm_model.fit(X_train, y_train)

  model_pred = svm_model.predict(X_test)
  end = process_time()

  print(model," train acc:",accuracy_score(y_true = y_train, y_pred=svm_model.predict(X_train)))
  print(model," test acc:",accuracy_score(y_true = y_test, y_pred=model_pred))
  print(model,"Recall :",(recall_score(y_true = y_test, y_pred=model_pred,)))
  print(model,"precision :",(precision_score(y_true = y_test, y_pred=model_pred,)))
  print(model,"F1 :",(f1_score(y_true = y_test, y_pred=model_pred,)))
  print(model,"Time :",str(end-start),"\n")

  model_list.append("SVM_"+model)
  model_test_acc.append(accuracy_score(y_true = y_test, y_pred=model_pred))
  model_train_acc.append(accuracy_score(y_true = y_train, y_pred=svm_model.predict(X_train)))
  model_recall.append(recall_score(y_true = y_test, y_pred=model_pred))
  model_precision.append(precision_score(y_true = y_test, y_pred=model_pred,))
  model_F1.append(f1_score(y_true = y_test, y_pred=model_pred,))
  model_time.append(str((end-start)))

linear  train acc: 0.9997582789460963
linear  test acc: 0.9603864734299516
linear Recall : 0.9367088607594937
linear precision : 0.9337539432176656
linear F1 : 0.9352290679304897
linear Time : 9.903995958000003

poly  train acc: 0.7592458303118201
poly  test acc: 0.7439613526570048
poly Recall : 0.17088607594936708
poly precision : 0.9473684210526315
poly F1 : 0.28954423592493295
poly Time : 29.868877932999993

rbf  train acc: 0.8100072516316171
rbf  test acc: 0.7951690821256039
rbf Recall : 0.38924050632911394
rbf precision : 0.8661971830985915
rbf F1 : 0.537117903930131
rbf Time : 36.17070423199999

sigmoid  train acc: 0.613246313753928
sigmoid  test acc: 0.629951690821256
sigmoid Recall : 0.33544303797468356
sigmoid precision : 0.37992831541218636
sigmoid F1 : 0.3563025210084033
sigmoid Time : 21.954464743999978

In [ ]:
df = pd.DataFrame(model_list, columns=['Models'])
df['test acc'] = model_test_acc
df['Recall '] = model_recall
df['prec_score'] = model_precision
df['F1_score'] = model_F1
df['Time '] = model_time


print("sorting by acc")
df.sort_values(by=['test acc'], ascending = False)

sorting by acc

          Models  test acc   Recall   prec_score  F1_score               Time
2     SVM_linear  0.960386  0.936709    0.933754  0.935229   9.903995958000003
0     GaussianNB  0.953623  0.939873    0.911043  0.925234  0.3719567710000007
1  MultinomialNB  0.948792  0.946203    0.892537  0.918587  0.1753831309999967
4        SVM_rbf  0.795169  0.389241    0.866197  0.537118   36.17070423199999
3       SVM_poly  0.743961  0.170886    0.947368  0.289544  29.868877932999993
5    SVM_sigmoid  0.629952  0.335443    0.379928  0.356303  21.954464743999978